# Estágio de Build
FROM maven:3.9-eclipse-temurin-17-alpine AS builder
WORKDIR /app
COPY pom.xml .
# Baixar dependências primeiro para aproveitar o cache do Docker
RUN mvn dependency:go-offline -B
COPY src ./src
RUN mvn package -DskipTests

# Estágio de Produção
FROM eclipse-temurin:17-jre-alpine
WORKDIR /app
# Copiar o JAR construído do estágio de build
COPY --from=builder /app/target/*.jar app.jar

# Variáveis de ambiente para configuração do banco de dados
# Estes valores podem ser sobrescritos pelo docker-compose.yml
ENV SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/listatarefas
ENV SPRING_DATASOURCE_USERNAME=postgres
ENV SPRING_DATASOURCE_PASSWORD=root
ENV SERVER_PORT=3000

EXPOSE 3000
ENTRYPOINT ["java","-jar","app.jar"]